import { ext, storageGet, storageSet } from '@/lib/browser';

/**
 * Runtime translation.
 *
 * `chrome.i18n` reads the browser's own language and cannot be overridden, so
 * an extension that lets the user pick a language has to carry its own lookup.
 * This module is that lookup: the generated message catalogues are bundled at
 * build time, and the active language is a stored preference rather than a
 * property of the browser.
 *
 * `chrome.i18n` still supplies the add-on name and description in the manifest
 * and in the browser's own add-on list, which the extension cannot restyle -
 * those follow the browser's language regardless of what is chosen here.
 */

/** Locale codes shipped with the extension, generated by scripts/locales.mjs. */
export const AVAILABLE_LOCALES = __LOCALE_CODES__;

/**
 * English is inlined so the first paint never waits on a network round trip,
 * and so a failed fetch still leaves a usable interface. Every other language
 * is fetched from the packaged _locales files on demand.
 *
 * Inlining all 55 was the obvious first attempt and made each bundle 250 KB -
 * fifty times the code it shipped, for languages a given user will never see.
 */
const CATALOGUES: Record<string, Record<string, string>> = {
  en: __LOCALE_MESSAGES_EN__,
};

/** Codes whose catalogue is present, so lookups can fall back knowingly. */
function isLoaded(locale: string): boolean {
  return CATALOGUES[locale] !== undefined;
}

/**
 * Loads one catalogue from the packaged locale files.
 *
 * The files are the same `_locales/<code>/messages.json` the browser reads for
 * `chrome.i18n`, so nothing is duplicated in the package. Their shape is
 * `{ key: { message } }`, which is flattened here.
 */
async function loadCatalogue(locale: string): Promise<void> {
  if (isLoaded(locale)) return;

  try {
    const url = ext.runtime.getURL(`_locales/${locale}/messages.json`);
    const response = await fetch(url);
    if (!response.ok) return;

    const raw = (await response.json()) as Record<string, { message?: string }>;
    const flat: Record<string, string> = {};
    for (const [key, entry] of Object.entries(raw)) {
      if (typeof entry?.message === 'string') flat[key] = entry.message;
    }
    CATALOGUES[locale] = flat;
  } catch {
    // A missing or malformed catalogue leaves English in place, which is a
    // readable interface rather than a broken one.
  }
}

/** English is the fallback for any key a locale does not translate. */
const FALLBACK_LOCALE = 'en';

const LANGUAGE_KEY = 'language';

/** The sentinel meaning "whatever the browser is set to". */
export const AUTO_LANGUAGE = 'auto';

let activeLocale = FALLBACK_LOCALE;

/**
 * Resolves a browser language tag to the closest catalogue we ship.
 *
 * The runtime reports hyphenated tags ("pt-BR"), while catalogues are keyed the
 * way the store expects ("pt_BR"), so the tag is normalised first. A regional
 * variant we do not carry falls back to its base language: "de-AT" to "de".
 */
export function resolveLocale(tag: string): string {
  const normalised = tag.replace('-', '_');
  if (AVAILABLE_LOCALES.includes(normalised)) return normalised;

  const base = normalised.split('_')[0];
  if (base && AVAILABLE_LOCALES.includes(base)) return base;

  return FALLBACK_LOCALE;
}

/** The browser's own UI language, resolved to a catalogue we ship. */
export function browserLocale(): string {
  try {
    return resolveLocale(ext.i18n?.getUILanguage?.() ?? FALLBACK_LOCALE);
  } catch {
    return FALLBACK_LOCALE;
  }
}

/**
 * Loads the stored language preference and makes it active.
 *
 * Call once before rendering any UI. Returns the stored preference itself
 * (which may be AUTO_LANGUAGE), not the resolved locale, so a settings screen
 * can show what the user actually chose.
 */
export async function initLocale(): Promise<string> {
  const stored = await readStoredLanguage();
  activeLocale = stored === AUTO_LANGUAGE ? browserLocale() : resolveLocale(stored);
  await loadCatalogue(activeLocale);
  return stored;
}

/** Switches the active language and remembers the choice. */
export async function setLanguage(language: string): Promise<void> {
  activeLocale = language === AUTO_LANGUAGE ? browserLocale() : resolveLocale(language);
  await loadCatalogue(activeLocale);
  await storageSet({ [LANGUAGE_KEY]: language });
}

async function readStoredLanguage(): Promise<string> {
  try {
    const result = await storageGet(LANGUAGE_KEY);
    const value = result[LANGUAGE_KEY];
    if (typeof value !== 'string') return AUTO_LANGUAGE;
    if (value === AUTO_LANGUAGE || AVAILABLE_LOCALES.includes(value)) return value;
    // A stored code we no longer ship should not strand the user in a language
    // with no catalogue behind it.
    return AUTO_LANGUAGE;
  } catch {
    return AUTO_LANGUAGE;
  }
}

/** The locale currently used for lookups. */
export function currentLocale(): string {
  return activeLocale;
}

/**
 * Looks up one message, falling back to English and then to the key itself.
 * Returning the key rather than an empty string makes a missing translation
 * visible instead of leaving a blank control.
 *
 * `substitutions` fills `$NAME$` placeholders, which some strings need because
 * the word order around an inserted name differs per language: English puts
 * the store last ("Rate on the Chrome Web Store"), Hungarian puts it in the
 * middle. Concatenating the pieces in code would force one order on all 55.
 */
export function t(
  key: string,
  fallback?: string,
  substitutions?: Record<string, string>,
): string {
  const message =
    CATALOGUES[activeLocale]?.[key] ??
    CATALOGUES[FALLBACK_LOCALE]?.[key] ??
    fallback ??
    key;

  if (!substitutions) return message;
  return message.replace(/\$([A-Z0-9_]+)\$/g, (placeholder, name: string) =>
    substitutions[name] ?? placeholder,
  );
}

/**
 * Applies translations to a document.
 *
 * Elements opt in with `data-i18n` for their text and `data-i18n-title` for a
 * tooltip, so markup stays declarative and re-running this after a language
 * change re-translates the whole page in place.
 */
export function applyTranslations(root: ParentNode = document): void {
  for (const node of root.querySelectorAll<HTMLElement>('[data-i18n]')) {
    const key = node.dataset.i18n;
    if (key) node.textContent = t(key, node.textContent ?? undefined);
  }
  for (const node of root.querySelectorAll<HTMLElement>('[data-i18n-title]')) {
    const key = node.dataset.i18nTitle;
    if (key) node.title = t(key, node.title);
  }
  for (const node of root.querySelectorAll<HTMLElement>('[data-i18n-label]')) {
    const key = node.dataset.i18nLabel;
    if (key) node.setAttribute('aria-label', t(key));
  }
}

/** Display names for the language picker, in each language's own script. */
export const LOCALE_NAMES: Record<string, string> = __LOCALE_NAMES__;
