#!/usr/bin/env node
/**
 * Source package builder.
 *
 * addons.mozilla.org requires a source archive whenever the submitted package
 * is produced by a bundler or minifier, so a reviewer can reproduce the exact
 * build. This writes dist/source-<version>.zip containing everything needed to
 * do that, and nothing that would only slow a reviewer down.
 *
 * Included: all sources, build scripts, configuration, lockfile, docs, license,
 * and a BUILD.md with step-by-step instructions at the archive root.
 * Excluded: node_modules, dist, .git, editor state - anything regenerated by
 * the documented build steps.
 *
 * Usage: node scripts/source-package.mjs
 */

import { createRequire } from 'node:module';
import { mkdir, readFile, readdir, rm, stat, writeFile } from 'node:fs/promises';
import path from 'node:path';
import process from 'node:process';
import { fileURLToPath } from 'node:url';
import { deflateRaw } from 'node:zlib';
import { promisify } from 'node:util';

const require = createRequire(import.meta.url);
const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const distDir = path.join(root, 'dist');
const deflate = promisify(deflateRaw);

/**
 * Directories and files kept out of the archive. Everything here is either
 * regenerated by the build or irrelevant to reproducing it.
 */
const EXCLUDED_DIRS = new Set([
  'node_modules',
  'dist',
  '.git',
  '.github/workflows/.cache',
  'coverage',
  '.vscode',
  '.idea',
  'build',
]);

const EXCLUDED_FILES = new Set([
  '.DS_Store',
  'Thumbs.db',
  '.eslintcache',
]);

const EXCLUDED_EXTENSIONS = new Set(['.zip', '.xpi', '.crx', '.pem', '.log']);

/**
 * The reviewer-facing build instructions, written to BUILD.md at the archive
 * root. AMO asks for the operating system and environment requirements, the
 * exact versions of the tools used, and a script that performs every step, so
 * all three are stated explicitly rather than left to be inferred.
 */
function buildInstructions(pkg) {
  return `# Build instructions

Source for **${pkg.name} ${pkg.version}**, submitted to addons.mozilla.org.

## Environment

| Requirement | Version |
| --- | --- |
| Operating system | Any of Linux, macOS or Windows. No platform-specific steps; the build was produced on Windows 10 and is reproducible on Linux. |
| Node.js | 20 or newer (tested on ${process.version}) |
| Package manager | npm 10+ (ships with Node 20), or pnpm 10+ / yarn - any of the three works |

No compiler toolchain, native modules or system libraries are required. Every
dependency is a pure JavaScript devDependency installed from the public npm
registry, and none of them ship in the add-on itself: the extension has zero
runtime dependencies.

## Steps

\`\`\`bash
# 1. Install the build dependencies (exact versions from the lockfile)
npm ci        # or: pnpm install --frozen-lockfile

# 2. Build every target and produce the store archives
npm run package
\`\`\`

That single command runs the full pipeline. The submitted file is:

\`\`\`
dist/firefox-mv2-${pkg.version}.zip
\`\`\`

To build only the Firefox targets:

\`\`\`bash
node scripts/build.mjs --target=firefox-mv2,firefox-mv3 --zip
\`\`\`

## What the build does

\`scripts/build.mjs\` is the single entry point. For each target it:

1. Bundles the TypeScript in \`src/\` with esbuild - one bundle per entry point
   (background, content script, popup, options). Standard esbuild minification
   is applied; no obfuscation, no name mangling beyond esbuild's defaults, and
   no code generation from templates.
2. Generates \`manifest.json\` via \`scripts/manifest.mjs\`, which emits the
   correct shape for the target browser and manifest version from one shared
   description. This is why the manifest is not checked in as a file.
3. Copies the static assets: the popup and options HTML/CSS from \`src/\`, and
   the icons and locale files from \`public/\`.
4. Optionally writes a plain zip of the result.

To inspect the unminified output, add \`--dev\`:

\`\`\`bash
node scripts/build.mjs --target=firefox-mv2 --dev
\`\`\`

This disables minification and inlines sourcemaps, producing readable code in
\`dist/firefox-mv2/\` that corresponds line by line to the sources in \`src/\`.

## Generated files under public/

Two directories in \`public/\` are generated rather than hand-written, and both
are committed so the build does not depend on regenerating them:

| Path | Generated by | From |
| --- | --- | --- |
| \`public/_locales/**\` | \`npm run locales\` | The single translation table in \`scripts/locales.mjs\` |
| \`public/icons/*.png\` | \`npm run icons\` | Vector drawing code in \`scripts/icons.mjs\`, encoded to PNG without an image library |

Running either script reproduces those files byte for byte. The CI workflow in
\`.github/workflows/ci.yml\` verifies this on every push.

## Verification

\`\`\`bash
npm run typecheck   # TypeScript, no errors
npm test            # unit tests
npm run lint        # ESLint
npm run lint:addon  # addons-linter against both Firefox builds
\`\`\`

## License

${pkg.license}. See LICENSE in this archive.

Source repository: ${pkg.repository?.url?.replace(/^git\+/, '').replace(/\.git$/, '') ?? 'see package.json'}
`;
}

/* -------------------------------------------------------------------------- */
/* Archive walking                                                             */
/* -------------------------------------------------------------------------- */

async function collect(dir, prefix = '', files = []) {
  for (const entry of await readdir(dir, { withFileTypes: true })) {
    const rel = prefix ? `${prefix}/${entry.name}` : entry.name;
    const full = path.join(dir, entry.name);

    if (entry.isDirectory()) {
      if (EXCLUDED_DIRS.has(entry.name) || EXCLUDED_DIRS.has(rel)) continue;
      await collect(full, rel, files);
      continue;
    }

    if (EXCLUDED_FILES.has(entry.name)) continue;
    if (EXCLUDED_EXTENSIONS.has(path.extname(entry.name))) continue;

    files.push({ path: rel, data: await readFile(full) });
  }
  return files;
}

/* -------------------------------------------------------------------------- */
/* ZIP writing (same minimal writer the build script uses)                     */
/* -------------------------------------------------------------------------- */

function buildCrcTable() {
  const table = new Int32Array(256);
  for (let i = 0; i < 256; i += 1) {
    let c = i;
    for (let k = 0; k < 8; k += 1) c = c & 1 ? 0xedb88320 ^ (c >>> 1) : c >>> 1;
    table[i] = c;
  }
  return table;
}

const CRC = buildCrcTable();

function crc32(buffer) {
  let crc = -1;
  for (let i = 0; i < buffer.length; i += 1) {
    crc = (crc >>> 8) ^ CRC[(crc ^ buffer[i]) & 0xff];
  }
  return (crc ^ -1) >>> 0;
}

async function writeZip(files, zipPath) {
  const chunks = [];
  const central = [];
  let offset = 0;

  for (const file of files) {
    const nameBytes = Buffer.from(file.path, 'utf8');
    const crc = crc32(file.data);
    const compressed = await deflate(file.data, { level: 9 });
    const useDeflate = compressed.length < file.data.length;
    const payload = useDeflate ? compressed : file.data;
    const method = useDeflate ? 8 : 0;

    const local = Buffer.alloc(30);
    local.writeUInt32LE(0x04034b50, 0);
    local.writeUInt16LE(20, 4);
    local.writeUInt16LE(0, 6);
    local.writeUInt16LE(method, 8);
    local.writeUInt16LE(0, 10);
    local.writeUInt16LE(0, 12);
    local.writeUInt32LE(crc, 14);
    local.writeUInt32LE(payload.length, 18);
    local.writeUInt32LE(file.data.length, 22);
    local.writeUInt16LE(nameBytes.length, 26);
    local.writeUInt16LE(0, 28);
    chunks.push(local, nameBytes, payload);

    const header = Buffer.alloc(46);
    header.writeUInt32LE(0x02014b50, 0);
    header.writeUInt16LE(20, 4);
    header.writeUInt16LE(20, 6);
    header.writeUInt16LE(0, 8);
    header.writeUInt16LE(method, 10);
    header.writeUInt16LE(0, 12);
    header.writeUInt16LE(0, 14);
    header.writeUInt32LE(crc, 16);
    header.writeUInt32LE(payload.length, 20);
    header.writeUInt32LE(file.data.length, 24);
    header.writeUInt16LE(nameBytes.length, 28);
    header.writeUInt16LE(0, 30);
    header.writeUInt16LE(0, 32);
    header.writeUInt16LE(0, 34);
    header.writeUInt16LE(0, 36);
    header.writeUInt32LE(0, 38);
    header.writeUInt32LE(offset, 42);
    central.push(header, nameBytes);

    offset += local.length + nameBytes.length + payload.length;
  }

  const centralBuffer = Buffer.concat(central);
  const end = Buffer.alloc(22);
  end.writeUInt32LE(0x06054b50, 0);
  end.writeUInt16LE(0, 4);
  end.writeUInt16LE(0, 6);
  end.writeUInt16LE(files.length, 8);
  end.writeUInt16LE(files.length, 10);
  end.writeUInt32LE(centralBuffer.length, 12);
  end.writeUInt32LE(offset, 16);
  end.writeUInt16LE(0, 20);

  await writeFile(zipPath, Buffer.concat([...chunks, centralBuffer, end]));
}

/* -------------------------------------------------------------------------- */

async function main() {
  const pkg = require('../package.json');
  await mkdir(distDir, { recursive: true });

  const zipPath = path.join(distDir, `source-${pkg.version}.zip`);
  await rm(zipPath, { force: true });

  const files = await collect(root);

  // BUILD.md sits at the archive root so a reviewer opening the zip sees the
  // instructions immediately, without hunting through docs/.
  files.push({
    path: 'BUILD.md',
    data: Buffer.from(buildInstructions(pkg), 'utf8'),
  });

  files.sort((a, b) => a.path.localeCompare(b.path));
  await writeZip(files, zipPath);

  const { size } = await stat(zipPath);
  console.log(`\nSource package for ${pkg.name} ${pkg.version}`);
  console.log(`  ${files.length} files`);
  console.log(`  ${(size / 1024).toFixed(1)} KB -> ${path.relative(root, zipPath)}`);

  // AMO rejects anything over 200 MB; warn long before that becomes a surprise.
  if (size > 200 * 1024 * 1024) {
    console.error('\nERROR: exceeds the 200 MB limit accepted by AMO.');
    process.exit(1);
  }
  console.log('\nUpload this file in the "Do You Need to Submit Source Code?" step.\n');
}

main().catch((error) => {
  console.error(error);
  process.exit(1);
});
